### ISSUE TITLE
README.md link to com.theoryinpractise....

### ISSUE THREAD

**Issue by Ingo60** [Frege/frege-lein-plugin#1]
Should we not use the new sonatype link?

**Comment by seancorfield** [comment]
It's not in Maven Central yet.

**Comment by Ingo60** [comment]
Hmmm ... excuse my ignorance, but shouldn't it be on sonatype-something? At least this is where I registered recently?

But wherever it is not yet .... why? And what to do about it?

**Comment by seancorfield** [comment]
Right, you publish to Sonatype and it should get promoted to Maven Central automatically (within a few hours generally). The latter is where everyone expects to find artifacts for releases -- although snapshots are pulled from Sonatype directly (and you shouldn't be building anything "production" from snapshots).

**Comment by talios** [comment]
I pushed http://search.maven.org/#artifactdetails%7Corg.frege-lang%7Cfrege%7C3.22.367-g2737683%7Cbundle awhile ago so this could be updated now.

**Comment by seancorfield** [comment]
Yup, been traveling too much lately to do any OSS project updates. It's on my list.

**Comment by seancorfield** [comment]
The plugin has been updated to 3.22.524 and now uses the Maven artifacts.
