### ISSUE TITLE
Inconsistency in clojars.org and frege-lein-plugin

### ISSUE THREAD

**Issue by DirkArnoldt** [Frege/frege-lein-plugin#11]
The lein-fregec plugin in Version 3.23.450 references the 
(def ^:private fregec-version "3.23.450-SNAPSHOT")
which does not exist in https://clojars.org/repo/org/frege-lang/frege/.

Could you please publish a version of this plugin that references an existing version of the frege compiler?

**Comment by seancorfield** [comment]
The SNAPSHOTs are published to Sonatype's OSS Snapshots repository because Clojars does not allow such large artifacts.
